title: "TFM: Desenvolupament d'un videojoc mòbil 2D amb Godot"
author: "Gemma Sellés Lloret"
date: today

lang: ca-ES

toc-depth: 6

number-sections: true

bibliography: Config/references.bib
csl: Config/apa.csl

# Activar els enllaços a nivell de Pandoc per a forçar el clic natiu
colorlinks: true
urlcolor: blue
linkcolor: blue

geometry:
  - left=3cm
  - right=2.5cm
  - top=2.5cm
  - bottom=2.5cm

fontsize: 12pt

linestretch: 1.5

pass-options-to-packages:
  - package: url
    options: hyphens

header-includes:
  - \sloppy

  - \newcommand{\keywordname}{Paraules clau}
  - \renewcommand{\contentsname}{Índex de continguts}
  - \renewcommand{\listfigurename}{Índex de figures}
  - \renewcommand{\listtablename}{Índex de taules}
  - \renewcommand{\figurename}{Figura}
  - \renewcommand{\tablename}{Taula}
  - \renewcommand{\abstractname}{Resum}

   # Paquete para gestionar PDFs externos
  - \usepackage{pdfpages}
  
  # Insertar la portada forzando a que el papel se adapte exactamente al PDF original
  - \AtBeginDocument{\includepdf[fitpaper=true, pages=1]{Config/portada.pdf}}
  
  # Crear la página en blanco obligatoria después de la portada
  - \AtBeginDocument{\thispagestyle{empty}\mbox{}\newpage}